/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
//import org.hsqldb.Tokens;



/**
 *
 * @author jagtap
 */
public class Admission extends javax.swing.JFrame {
    private byte[] person_image;

    /**
     * Creates new form Admission
     */
    public Admission() {
        initComponents();
//        this.setSize(1000, 800);
  this.setSize(1938,1048);
// firstname.setText("Enter name");
        TextPrompt t = new TextPrompt("Enter Fristname", firstname);
       TextPrompt tt = new TextPrompt("Enter Surname", surname);
       TextPrompt t2 = new TextPrompt("Enter Email", email);
       TextPrompt t3 = new TextPrompt("Enter Telephone no ", tele);
       TextPrompt t4 = new TextPrompt("Enter Pincode", pin);
       TextPrompt t5 = new TextPrompt("Choose Date Of Brith", dob);
       TextPrompt t6 = new TextPrompt("Enter Address", address);
       TextPrompt t7 = new TextPrompt("Enter Address", add2);
       TextPrompt t8 = new TextPrompt("Enter House No ", apt);
       
       
      
            
    }
String ImgPath = null;
String s;


    public ImageIcon ResizeImage(String imagepath,byte[] pic)
    {
      ImageIcon myImage=null;  
      
      if(imagepath != null)
      {
          myImage = new ImageIcon(imagepath);
          
      }
      else
      {
          myImage =new ImageIcon(pic);
      }
      Image img = myImage.getImage();
      Image img2 = img.getScaledInstance(lbl_pic.getWidth(), lbl_pic.getHeight(), Image.SCALE_SMOOTH);
              ImageIcon image =new ImageIcon(img2);
              return image;
              
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tele = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        dob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        apt = new javax.swing.JTextField();
        add2 = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        medi = new javax.swing.JComboBox();
        btn_upload = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_pic = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblf = new javax.swing.JLabel();
        lbls = new javax.swing.JLabel();
        lblem = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblpin = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(997, 602));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 36))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact Number :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(270, 450, 110, 14);

        tele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleFocusLost(evt);
            }
        });
        tele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleActionPerformed(evt);
            }
        });
        tele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teleKeyPressed(evt);
            }
        });
        jPanel3.add(tele);
        tele.setBounds(420, 440, 168, 30);

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        jPanel3.add(email);
        email.setBounds(420, 400, 168, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(270, 410, 60, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(270, 370, 70, 14);

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel3.add(r_male);
        r_male.setBounds(420, 370, 47, 23);

        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel3.add(r_female);
        r_female.setBounds(480, 370, 59, 23);

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobKeyPressed(evt);
            }
        });
        jPanel3.add(dob);
        dob.setBounds(420, 330, 168, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Birth :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 340, 100, 14);

        surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameFocusLost(evt);
            }
        });
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });
        surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surnameKeyPressed(evt);
            }
        });
        jPanel3.add(surname);
        surname.setBounds(420, 290, 168, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Surname :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(270, 300, 80, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First name :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(270, 260, 90, 14);

        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnameKeyPressed(evt);
            }
        });
        jPanel3.add(firstname);
        firstname.setBounds(420, 250, 168, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address Line 1 :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(270, 490, 110, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address Line 2 :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(270, 530, 110, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Apt./House No :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(270, 570, 110, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pin Code :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(270, 610, 80, 20);

        pin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinFocusLost(evt);
            }
        });
        jPanel3.add(pin);
        pin.setBounds(420, 600, 168, 30);

        apt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptActionPerformed(evt);
            }
        });
        jPanel3.add(apt);
        apt.setBounds(420, 560, 168, 30);
        jPanel3.add(add2);
        add2.setBounds(420, 520, 168, 30);

        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        jPanel3.add(address);
        address.setBounds(420, 480, 168, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mediam:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(270, 650, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student ID :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(270, 220, 90, 14);

        studentid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        studentid.setName(""); // NOI18N
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });
        jPanel3.add(studentid);
        studentid.setBounds(420, 210, 168, 30);

        medi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Semi-English", "Marathi" }));
        medi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediActionPerformed(evt);
            }
        });
        jPanel3.add(medi);
        medi.setBounds(420, 640, 168, 30);

        btn_upload.setText("Upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel3.add(btn_upload);
        btn_upload.setBounds(834, 517, 90, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(420, 700, 70, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(520, 700, 70, 40);

        lbl_pic.setBackground(new java.awt.Color(0, 0, 0));
        lbl_pic.setOpaque(true);
        jPanel3.add(lbl_pic);
        lbl_pic.setBounds(779, 252, 186, 168);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 180, 50, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "5th", "6th", "7th", "8th", "9th", "10th" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(420, 180, 80, 20);

        lblf.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblf);
        lblf.setBounds(1221, 662, 0, 0);

        lbls.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbls);
        lbls.setBounds(1221, 668, 0, 0);

        lblem.setForeground(new java.awt.Color(255, 255, 255));
        lblem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblemFocusLost(evt);
            }
        });
        jPanel3.add(lblem);
        lblem.setBounds(1221, 760, 0, 0);

        lblno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblno);
        lblno.setBounds(1221, 771, 0, 0);

        lblpin.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblpin);
        lblpin.setBounds(618, 891, 0, 0);

        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel3.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(606, 329, 155, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\signup-icon.png")); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 200, 265);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(280, 700, 100, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\oooooooo.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(0, -10, 1930, 1050);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1940, 1060);

        setSize(new java.awt.Dimension(1954, 1087));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        String gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        String gender;
        gender = "Female";
        r_female.setSelected(true);
        r_male.setSelected(false);

    }//GEN-LAST:event_r_femaleActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void aptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      //    if (add2.getText().isEmpty()||
//studentid.getText() .isEmpty()|| firstname.getText() .isEmpty()||surname.getText() .isEmpty()||dob.getText() .isEmpty()||email.getText() .isEmpty()||tele.getText() .isEmpty()||address.getText() .isEmpty()||apt.getText() .isEmpty()||pin.getText() .isEmpty())
        //{
            //JOptionPane.showMessageDialog(null, "Please Enter all Details");
       // }
        Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
 String gender = null;
 String R =jComboBox1.getSelectedItem().toString(); 
 //String t = "5th";
 try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
       if ( jComboBox1.getSelectedItem().toString().equals("5th") ) {
    String sql= "Insert into fifth (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
   pst.setString(13,s);
  
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
       String dd =  ("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\student\\"+studentid.getText()+","+jComboBox1.getSelectedItem().toString() +".jpg");
                
               // Files.copy(ss, dd,StandardCopyOption.COPY_ATTRIBUTES);
                Files.copy(Paths.get(s), Paths.get(dd),StandardCopyOption.COPY_ATTRIBUTES);
   JOptionPane.showMessageDialog(null,"Saved");
  
               
     this.setVisible(false);
     new feepayment().setVisible(true);
         
       }
        if (jComboBox1.getSelectedItem().toString().equals("6th")) {
     String sql= "Insert into sixth (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
   pst.setString(13,s  );
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
       String dd =  ("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\student\\"+studentid.getText()+","+jComboBox1.getSelectedItem().toString() +".jpg");
                
               // Files.copy(ss, dd,StandardCopyOption.COPY_ATTRIBUTES);
               
               Files.copy(Paths.get(s), Paths.get(dd),StandardCopyOption.COPY_ATTRIBUTES);
   JOptionPane.showMessageDialog(null,"Saved");
               
     this.setVisible(false);
     new feepayment().setVisible(true);       
          
     }
 
 
               if (jComboBox1.getSelectedItem().toString().equals("7th")){
            
     
     String sql= "Insert into seventh (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
     pst.setString(13,s  );
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
   String dd =  ("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\student\\"+studentid.getText()+","+jComboBox1.getSelectedItem().toString() +".jpg");
                
               // Files.copy(ss, dd,StandardCopyOption.COPY_ATTRIBUTES);
                Files.copy(Paths.get(s), Paths.get(dd),StandardCopyOption.COPY_ATTRIBUTES);
       JOptionPane.showMessageDialog(null,"Saved");
               
     this.setVisible(false);
         new feepayment().setVisible(true);
            }
 
             if (jComboBox1.getSelectedItem().toString().equals("8th")) {
                 // String sql= "Insert into eigth (stud_ID,stud_fname,stud_lname,stud_surname,dob,gender,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
                  String sql= "Insert into eigth (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
      pst.setString(13,s  );
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
   JOptionPane.showMessageDialog(null,"Saved");
               
     this.setVisible(false);
      new feepayment().setVisible(true);
         
     }  
    
            if (jComboBox1.getSelectedItem().toString().equals("9th")) {
                 String sql= "Insert into ninth (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
      pst.setString(13,s  );
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
  String dd =  ("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\student\\"+studentid.getText()+","+jComboBox1.getSelectedItem().toString() +".jpg");
                
               // Files.copy(ss, dd,StandardCopyOption.COPY_ATTRIBUTES);
                Files.copy(Paths.get(s), Paths.get(dd),StandardCopyOption.COPY_ATTRIBUTES);
       JOptionPane.showMessageDialog(null,"Saved");
               
     this.setVisible(false);
 new feepayment().setVisible(true);
         
         } 
  
     if (jComboBox1.getSelectedItem().toString().equals("10th"))
            {
      String sql= "Insert into tenth (stud_ID,stud_fname,stud_lname,dob,gender,email,contact,address1,address2,houseno,pincode,mediam,pic) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";
   pst=con.prepareStatement(sql);
   InputStream is = new FileInputStream(new File (s));
   pst.setString(1,studentid.getText());
   pst.setString(2,firstname.getText());
   pst.setString(3,surname.getText());
   pst.setString(4,dob.getText());
   if(r_male.isSelected())
   {
          gender = "Male";
   }
   if(r_female.isSelected())
   {
          gender = "female";
   }
   pst.setString(5,gender);
   pst.setString(6,email.getText());
   pst.setString(7,tele.getText());
   pst.setString(8,address.getText());
   pst.setString(9,add2.getText());
   pst.setString(10,apt.getText());
   pst.setString(11,pin.getText());
   pst.setString(12,medi.getSelectedItem().toString());
       pst.setString(13,s  );
   pst.executeUpdate();
   InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\save.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
       
                String dd =  ("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\student\\"+studentid.getText()+","+jComboBox1.getSelectedItem().toString() +".jpg");
                
               // Files.copy(ss, dd,StandardCopyOption.COPY_ATTRIBUTES);
                Files.copy(Paths.get(s), Paths.get(dd),StandardCopyOption.COPY_ATTRIBUTES);
   JOptionPane.showMessageDialog(null,"Saved");
               
     this.setVisible(false);
            new feepayment().setVisible(true);
            }
            
 }catch( Exception e ) {       
      
                JOptionPane.showMessageDialog(null, "Please Enter all Details","ERROR", JOptionPane.ERROR_MESSAGE);
           JOptionPane.showMessageDialog(null, e);
 
 
 }       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter(("*.image"), "jpg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            
            try {
                File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                // path ss=new Path(""+selectedFile.getAbsoluteFile());
                //Path sss=ne(""+selectedFile.getAbsoluteFile());
                s=path;
                String ss= selectedFile.getAbsolutePath();
                
//copy source to target using Files Class
                
                lbl_pic.setIcon(ResizeImage(path,null));
            } catch (Exception ex) {
                //Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
            }
          

                  }
        else
        {
            System.out.println("no file selected");
        }
            
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new MainMenu().setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyPressed
        // char ch= keyDown(evt, WIDTH);
       // int KeyAscii=ch ;   
        //if (KeyAscii > 65 && KeyAscii <= 90 || KeyAscii >= 97 && KeyAscii <= 122 || KeyAscii = 32 || KeyAscii = 8) 
        //{
            
        //} else {
        //}
    }//GEN-LAST:event_firstnameKeyPressed

    private void surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameKeyPressed

       // TODO add your handling code here:
    }//GEN-LAST:event_surnameKeyPressed

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed

            
            // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyPressed

    private void dateChooserCombo1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnSelectionChange
    
      // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1OnSelectionChange

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
          // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyPressed

    private void teleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleKeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_teleKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
 
    }//GEN-LAST:event_addressKeyPressed

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
 String regx = "^[\\p{L} .'-]+$";
  
     Pattern pattern = Pattern.compile(regx,Pattern.CASE_INSENSITIVE);
      Matcher matcher = pattern.matcher(firstname.getText());
   
         if (firstname.getText().matches(regx)) {
        //JOptionPane.showMessageDialog(null,"HII");
        lblf.setText(" ");
              } else {
              lblf.setText("Enter Character only");
                   lblf.setForeground(Color.red);
             //setCursor();
        
                     }
          // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFocusLost

    private void surnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFocusLost
String regx = "^[\\p{L} .'-]+$";
        
       Pattern pattern = Pattern.compile(regx,Pattern.CASE_INSENSITIVE);
     Matcher matcher = pattern.matcher(surname.getText());
      
     if (surname.getText().matches(regx)) {
     lbls.setText(" ");
         //JOptionPane.showMessageDialog(null,"HII");
        } else {
            lbls.setText("Enter Character only");
       lbls.setForeground(Color.red);
      
     
    }// TODO add your handling code here:
    }//GEN-LAST:event_surnameFocusLost

    private void lblemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblemFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblemFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        String regx = "^[\\p{L} .'-]+$";
String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
         Pattern p = Pattern.compile(ePattern);
         Matcher m = p.matcher(email.getText());
      if (email.getText().matches(ePattern)) {
      lblem.setText(" ");  
//JOptionPane.showMessageDialog(null,"HII");
        } else {
            lblem.setText("Enter Vailid Email only");
       lblem.setForeground(Color.red);
      
     
    }

// TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    private void teleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleFocusLost
String regexStr = "^[0-9]{10}$";
Pattern pattern = Pattern.compile(regexStr,Pattern.CASE_INSENSITIVE);
    Matcher matcher = pattern.matcher(tele.getText());
    if (tele.getText().matches(regexStr)) {
       lblno.setText(" ");
        //JOptionPane.showMessageDialog(null,"HII");
        
    } else 
    {
        lblno.setText("Enter Vaild Phone no only");
        lblno.setForeground(Color.red);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_teleFocusLost

    private void pinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinFocusLost
String regexStr = "^[0-9]{6}$";
Pattern pattern = Pattern.compile(regexStr,Pattern.CASE_INSENSITIVE);
    Matcher matcher = pattern.matcher(pin.getText());
    if (pin.getText().matches(regexStr)) {
       lblpin.setText(" ");
        //JOptionPane.showMessageDialog(null,"HII");
        
    } else 
    {
        lblpin.setText("Enter Vaild PIN Code only");
        lblpin.setForeground(Color.red);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_pinFocusLost

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
String s = dateChooserCombo1.getText();
    
            
      dob.setText(dateChooserCombo1.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Connection con = null;
     PreparedStatement pst = null;
     ResultSet rs =null;
 try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
if(jComboBox1.getSelectedItem().toString().equals("5th"))
 {
        String sql="Select max(stud_ID) from fifth  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;
//JOptionPane.showMessageDialog(null, b);
studentid.setText(String.valueOf(b));
        }
 }else
      
  if(jComboBox1.getSelectedItem().toString().equals("6th"))
 {
  
     String sql="Select max(stud_ID) from sixth  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
         while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;

studentid.setText(String.valueOf(b));
        }
 }else
         if(jComboBox1.getSelectedItem().toString().equals("7th"))
      {
        String sql="Select max(stud_ID) from seventh  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;

	studentid.setText(String.valueOf(b));
        
        }
      }else
        
     
        if(jComboBox1.getSelectedItem().toString().equals("8th"))
 {
        String sql="Select max(stud_ID) from eigth  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;

studentid.setText(String.valueOf(b));
        }
 }else
        
        if(jComboBox1.getSelectedItem().toString().equals("9th"))
 {
        String sql="Select max(stud_ID) from ninth  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;

	studentid.setText(String.valueOf(b));
        }
 }else
         
        if(jComboBox1.getSelectedItem().toString().equals("10th"))
 {
        String sql="Select max(stud_ID) from tenth  ";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           
            int a= Integer.parseInt(rs.getString(1));
            int b = a+1;

studentid.setText(String.valueOf(b));
        }
 }
 
 }catch(Exception e ){
     JOptionPane.showMessageDialog(null, e);
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void mediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediActionPerformed

    private void teleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admission().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add2;
    private javax.swing.JTextField address;
    private javax.swing.JTextField apt;
    private javax.swing.JButton btn_upload;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_pic;
    private javax.swing.JLabel lblem;
    private javax.swing.JLabel lblf;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblpin;
    private javax.swing.JLabel lbls;
    private javax.swing.JComboBox medi;
    private javax.swing.JTextField pin;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tele;
    // End of variables declaration//GEN-END:variables

    private Icon ResizeImage(String path) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
      private ImageIcon format =null;
    //strin filename
    String filename = null;
    byte[] person_images = null;

    private char keyDown(KeyEvent evt, int WIDTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
