/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jagtap
 */
public class Fergotpass extends javax.swing.JFrame {

    /**
     * Creates new form Fergotpass
     */
    public Fergotpass() {
       // jLabel2.setVisible(false);
        initComponents();
        this.setSize(518, 430);
      //jButton1.setBackground(Color.Purple);
      TextPrompt t = new TextPrompt("Enter Username", usernm);
       TextPrompt tt = new TextPrompt("Enter Your Answer", ans);
       TextPrompt t1 = new TextPrompt("Enter Conform Password", cps);
       TextPrompt t2 = new TextPrompt("Enter Password",nps);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
         ans.setVisible(false);
          jButton2.setVisible(false);
          jLabel4.setVisible(false);
            nps.setVisible(false);
           jLabel5.setVisible(false);
            cps.setVisible(false);
             jButton3.setVisible(false);
             jButton4.setVisible(false);
             jButton1.setBackground(Color.black);
             jButton2.setBackground(Color.black);
             jButton3.setBackground(Color.black);
             jButton4.setBackground(Color.black);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nps = new javax.swing.JPasswordField();
        cps = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 120, 20);

        usernm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        getContentPane().add(usernm);
        usernm.setBounds(84, 21, 173, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Security Question");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 61, 110, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("What is the year of starting M.E.S Boys High School ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 81, 290, 14);
        getContentPane().add(ans);
        ans.setBounds(72, 101, 256, 30);

        jButton1.setBackground(new java.awt.Color(102, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 20, 70, 23);

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(72, 139, 80, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 207, 90, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Conform Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 250, 110, 14);
        getContentPane().add(nps);
        nps.setBounds(122, 204, 198, 30);
        getContentPane().add(cps);
        cps.setBounds(123, 251, 197, 30);

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(52, 300, 70, 23);

        jButton4.setBackground(new java.awt.Color(102, 0, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(174, 300, 80, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 0, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\wallpapersden.com_purple-blur_950x1534.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 520, 770);

        setSize(new java.awt.Dimension(518, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con =null;
        PreparedStatement pst=null;
        ResultSet rs =null;
        try{
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
        String sql="Select * from login where usernm='"+usernm.getText()+"'";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "Username Found");
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            ans.setVisible(true);
            jButton2.setVisible(true);
                    
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Username NOT Found");
        }
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con =null;
        PreparedStatement pst=null;
        ResultSet rs =null;
        try{
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
        String sql="Select * from login where que='"+ans.getText()+"'";
        pst=con.prepareCall(sql);
        rs=pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "Correct Answer");
             jLabel4.setVisible(true);
            nps.setVisible(true);
           jLabel5.setVisible(true);
            cps.setVisible(true);
             jButton3.setVisible(true);
             jButton4.setVisible(true);
                    
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Wrong Answer Try Again");
        }
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Connection con =null;
        PreparedStatement pst=null;
        ResultSet rs =null;
        
        try{
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
        String sql ="Update  login set  password = '"+cps.getText()+"'where usernm =  '"+usernm.getText()+"'";
        pst=con.prepareCall(sql);
        pst.executeUpdate();
      
        
            JOptionPane.showMessageDialog(null, "Update Successfuly");
            
                    
        
        
            
        
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Can't change password , please try again");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Fergotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JPasswordField cps;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField nps;
    private javax.swing.JTextField usernm;
    // End of variables declaration//GEN-END:variables
}
