/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


import java.awt.Dimension;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.export.ExporterInput;
import net.sf.jasperreports.export.OutputStreamExporterOutput;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.export.SimplePdfExporterConfiguration;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jagtap
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        //this.setUndecorated(true);
       // this.setAlwaysOnTop(true);
       // this.setVisible(true);
        initComponents();
        //jLabel2.setText(nm);
       
        //jLabel2.setText();
        Dimension d = this.getSize();
      this.setSize(d);
   
        }
    public MainMenu( String sg ) {
        //this.setUndecorated(true);
       // this.setAlwaysOnTop(true);
       // this.setVisible(true);
        initComponents();
        //jLabel2.setText("Welcome "+sg);
       
        //jLabel2.setText();
      this.setSize(1024, 562);
   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem8.setText("jMenuItem8");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("jMenu8");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1810, 40, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Pictures\\3 - Copy.jpg")); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1938, 1023);

        jMenu9.setText("Addmission ");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Search");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        jMenu11.setText("Update");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu11);

        jMenu1.setText("Report");

        jMenuItem1.setText("Fifth");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sixth");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Seventh");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Eigth");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Ninth");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Tenth");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("About");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu2.setText("Exit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1954, 1087));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        Dashboard db = new Dashboard();
        this.setVisible(false);
         db.setVisible(true);
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
  Admission aa = new Admission();
        this.setVisible(false);
        aa.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Fifth.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
        File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
        outDir.mkdirs();
 
        // PDF Exportor.
        JRPdfExporter exporter = new JRPdfExporter();
 
        ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
                "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\fifth.pdf");
        // Output
        exporter.setExporterOutput(exporterOutput);
 
        //
        SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        exporter.setConfiguration(configuration);
        exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\tenth.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
//        File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
  //      outDir.mkdirs();
 
        // PDF Exportor.
    //    JRPdfExporter exporter = new JRPdfExporter();
 
      //  ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        //exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        //OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
          //      "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\seventh.pdf");
        // Output
        //exporter.setExporterOutput(exporterOutput);
 
        //
        SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        //exporter.setConfiguration(configuration);
        //exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\sixth.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
 //       File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
   //     outDir.mkdirs();
 
        // PDF Exportor.
     //   JRPdfExporter exporter = new JRPdfExporter();
 
       // ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        //exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        //OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
               // "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\sixth.pdf");
        // Output
        //exporter.setExporterOutput(exporterOutput);
 
        //
        //SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        //exporter.setConfiguration(configuration);
        //exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\seventh.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
//        File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
  //      outDir.mkdirs();
 
        // PDF Exportor.
    //    JRPdfExporter exporter = new JRPdfExporter();
 
      //  ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        //exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        //OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
          //      "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\seventh.pdf");
        // Output
        //exporter.setExporterOutput(exporterOutput);
 
        //
        SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        //exporter.setConfiguration(configuration);
        //exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\eigth.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
//        File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
  //      outDir.mkdirs();
 
        // PDF Exportor.
    //    JRPdfExporter exporter = new JRPdfExporter();
 
      //  ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        //exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        //OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
          //      "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\seventh.pdf");
        // Output
        //exporter.setExporterOutput(exporterOutput);
 
        //
       // SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        //exporter.setConfiguration(configuration);
        //exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
                                              
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
Connection con = null;
    PreparedStatement pst = null;
 ResultSet rs =null;
        try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
     con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
  
     
     String reportSrcFile = "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\src\\javaapplication1\\ninth.jrxml";
         
        // First, compile jrxml file.
        JasperReport jasperReport =    JasperCompileManager.compileReport(reportSrcFile);
 
         
 
        // Parameters for report
        Map<String, Object> parameters = new HashMap<String, Object>();
 
        JasperPrint print = JasperFillManager.fillReport(jasperReport,
                parameters, con);
 
        // Make sure the output directory exists.
//        File outDir = new File("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report");
  //      outDir.mkdirs();
 
        // PDF Exportor.
    //    JRPdfExporter exporter = new JRPdfExporter();
 
      //  ExporterInput exporterInput = new SimpleExporterInput(print);
        // ExporterInput
        //exporter.setExporterInput(exporterInput);
 
        // ExporterOutput
        //OutputStreamExporterOutput exporterOutput = new SimpleOutputStreamExporterOutput(
          //      "C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Report\\seventh.pdf");
        // Output
        //exporter.setExporterOutput(exporterOutput);
 
        //
        SimplePdfExporterConfiguration configuration = new SimplePdfExporterConfiguration();
        //exporter.setConfiguration(configuration);
        //exporter.exportReport();
        JasperViewer.viewReport(print);
 
        System.out.print("Done!");
    

 
 
 
 }catch(Exception e ){}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
this.setVisible(false);
new Search().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
this.setVisible(false);
new Update().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
new NewJFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
this.setVisible(false);// TODO add your handling code here:
new Dashboard().setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

    private void setsize(int xsize, int ysize) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
