package javaapplication1;

import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartUp.java
 *
 * Created on 30 Oct, 2016, 6:46:24 PM
 */

/**
 *
 * @author Abhishek
 */
public class StartUp1 extends javax.swing.JFrame implements Runnable {

    Thread t = null;

    /** Creates new form StartUp */
    public StartUp1() {
      //  t.start();

        //super("Welcome to School Management System");

        initComponents();

        
        this.setLocationRelativeTo(null);
                //  JOptionPane.showMessageDialog(null, "1234");
        try {
        Thread t=Thread.currentThread();
   
            t.sleep(1000);
            
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(null, "hii");
       }     this.dispose();
        
      // t.sleep(1000);
            //JOptionPane.showMessageDialog(null, "5678");
         //this.setVisible(false);
    }
        //-----
                  
        
         //this.setVisible(true);
        
        
        
        
        

 //extends javax.swing.JFrame implements Runnable {
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(52, 86, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loading Please Wait", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jProgressBar1.setBackground(new java.awt.Color(52, 86, 51));
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(401, 246));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(340, 256));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/_pencil.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -160, 400, 530);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 200, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    /*public static void main(String args[]) throws InterruptedException {

         StartUp1 s =new StartUp1();
         s.setVisible(true);
         Thread t=Thread.currentThread();
         JOptionPane.showMessageDialog(null, "1234");
         t.sleep(1000);
         JOptionPane.showMessageDialog(null, "5678");
         s.dispose();
         new MainMenu().setVisible(true);
java.awt.EventQueue.invokeLater(new Runnable() {
        
*/
            public void run()  
            {
     
        
                
            }
        
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
};
