/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Dell
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    this.setSize(1938,1048);
    this.setLocationRelativeTo(null);
    TextPrompt t1 = new TextPrompt("Enter Student Id", txtsearch);
    }
     String s;
     public ImageIcon ResizeImage(String imagepath,byte[] pic)
    {
      ImageIcon myImage=null;  
      
      if(imagepath != null)
      {
          myImage = new ImageIcon(imagepath);
          
      }
      else
      {
          myImage =new ImageIcon(pic);
      }
      Image img = myImage.getImage();
      Image img2 = img.getScaledInstance(lbl_pic.getWidth(), lbl_pic.getHeight(), Image.SCALE_SMOOTH);
              ImageIcon image =new ImageIcon(img2);
              return image;
              
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        add2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        tele = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        lbl_pic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        apt = new javax.swing.JTextField();
        pin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        medi = new javax.swing.JComboBox();
        btn_upload = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 20, 70, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "5th", "6th", "7th", "8th", "9th", "10th" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 20, 100, 20);

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch);
        txtsearch.setBounds(30, 50, 480, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 80, 20);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(530, 50, 90, 40);

        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnameKeyPressed(evt);
            }
        });
        getContentPane().add(firstname);
        firstname.setBounds(130, 110, 168, 30);
        getContentPane().add(add2);
        add2.setBounds(130, 390, 168, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address Line 2 :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 400, 100, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address Line 1 :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 360, 100, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact Number :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 100, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 50, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 240, 60, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Birth :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 90, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Surname :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 160, 70, 20);

        surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameFocusLost(evt);
            }
        });
        surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surnameKeyPressed(evt);
            }
        });
        getContentPane().add(surname);
        surname.setBounds(130, 150, 168, 30);

        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobKeyPressed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(130, 190, 168, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 230, 170, 30);

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(130, 270, 168, 30);

        tele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleFocusLost(evt);
            }
        });
        tele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleActionPerformed(evt);
            }
        });
        tele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teleKeyPressed(evt);
            }
        });
        getContentPane().add(tele);
        tele.setBounds(130, 310, 168, 30);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(130, 350, 168, 30);

        lbl_pic.setBackground(new java.awt.Color(204, 204, 204));
        lbl_pic.setOpaque(true);
        getContentPane().add(lbl_pic);
        lbl_pic.setBounds(490, 120, 186, 168);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mediam:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 510, 60, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pin Code :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 480, 70, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Apt./House No :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 440, 100, 14);

        apt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptActionPerformed(evt);
            }
        });
        getContentPane().add(apt);
        apt.setBounds(130, 430, 168, 30);

        pin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinFocusLost(evt);
            }
        });
        getContentPane().add(pin);
        pin.setBounds(130, 470, 168, 30);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 560, 100, 30);

        medi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Semi-English", "Marathi" }));
        getContentPane().add(medi);
        medi.setBounds(130, 510, 168, 30);

        btn_upload.setText("Upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_upload);
        btn_upload.setBounds(532, 300, 90, 23);

        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(320, 190, 155, 30);

        jButton2.setText("Update photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 560, 150, 30);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 560, 80, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Pictures\\1.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-160, -50, 2100, 1100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs =null;
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
            if (jComboBox1.getSelectedItem().toString().equals("5th")) {
                String sql= "select * from fifth where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                   // jTextField2.setText(rs.getString(11));
                    medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
                       }
            

            if (jComboBox1.getSelectedItem().toString().equals("6th")) {
                String sql= "select * from sixth where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
              
                while(rs.next())
                {
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                    //jTextField2.setText(rs.getString(11));
                        medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
            }

            if (jComboBox1.getSelectedItem().toString().equals("7th")) {
                String sql= "select * from seventh where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
               
                while(rs.next())
                {
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                    //jTextField2.setText(rs.getString(11));
                    medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
            }

            if (jComboBox1.getSelectedItem().toString().equals("8th")) {
                String sql= "select * from eigth where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                    //jTextField2.setText(rs.getString(11));
                    medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
            }

            if (jComboBox1.getSelectedItem().toString().equals("9th")) {
                String sql= "select * from ninth where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                    //jTextField2.setText(rs.getString(11));
                    medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
            }

            if (jComboBox1.getSelectedItem().toString().equals("10th")) {
                String sql= "select * from tenth where stud_ID = '"+txtsearch.getText()+"' ";
                pst=con.prepareCall(sql);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    
                    firstname.setText(rs.getString(1));
                    surname.setText(rs.getString(2));
                    dob.setText(rs.getString(3));
                    jTextField1.setText(rs.getString(4));
                    email.setText(rs.getString(5));
                    tele.setText(rs.getString(6));
                    address.setText(rs.getString(7));
                    add2.setText(rs.getString(8));
                    apt.setText(rs.getString(9));
                    pin.setText(rs.getString(10));
                  //  jTextField2.setText(rs.getString(11));
                  medi.setSelectedItem(rs.getString(11));
                    lbl_pic.setIcon(ResizeImage(rs.getNString("pic"),null));
                }
            }

        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyPressed
        // char ch= keyDown(evt, WIDTH);
        // int KeyAscii=ch ;
        //if (KeyAscii > 65 && KeyAscii <= 90 || KeyAscii >= 97 && KeyAscii <= 122 || KeyAscii = 32 || KeyAscii = 8)
        //{

            //} else {
            //}
    }//GEN-LAST:event_firstnameKeyPressed

    private void surnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameFocusLost

    private void surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_surnameKeyPressed

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyPressed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyPressed

    private void teleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_teleFocusLost

    private void teleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed

    }//GEN-LAST:event_addressKeyPressed

    private void aptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptActionPerformed

    private void pinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinFocusLost

    }//GEN-LAST:event_pinFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//String sql= "select * from tenth where stud_ID = '"+txtsearch.getText()+"' ";
Connection con = null;
PreparedStatement pst = null;
PreparedStatement pst1 = null;
 ResultSet rs =null;
 try {
    
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
                if (jComboBox1.getSelectedItem().toString().equals("5th")) {
                String sql ="Update  fifth set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
        
   //rs=pst1.executeQuery();
   // InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }
        if (jComboBox1.getSelectedItem().toString().equals("6th")) {
                String sql ="Update  sixth set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    //InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }
if (jComboBox1.getSelectedItem().toString().equals("7th")) {
                String sql ="Update  seventh set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    //InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }
if (jComboBox1.getSelectedItem().toString().equals("8th")) {
                String sql ="Update  eight set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    //InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }
if (jComboBox1.getSelectedItem().toString().equals("9th")) {
                String sql ="Update  ninth set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    //InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }
if (jComboBox1.getSelectedItem().toString().equals("10th")) {
                String sql ="Update  tenth set stud_fname=?,stud_lname=?,dob=?,email=?,contact=?,address1=?,address2=?,houseno=?,pincode=?,mediam= ? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    //InputStream is = new FileInputStream(new File (s));
        pst.setString(1,firstname.getText());
        pst.setString(2,surname.getText());
        pst.setString(3,dob.getText());
    
   pst.setString(4,email.getText());
   pst.setString(5,tele.getText());
   pst.setString(6,address.getText());
   pst.setString(7,add2.getText());
   pst.setString(8,apt.getText());
   pst.setString(9,pin.getText());
   pst.setString(10,medi.getSelectedItem().toString());
    // pst.setString(11,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
            InputStream music;
       music = new FileInputStream("C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\update.wav");
       AudioStream a =new AudioStream(music);
       AudioPlayer.player.start(a);
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
            }




           
 }catch(Exception e){ JOptionPane.showMessageDialog(null, e); }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));
         file.setCurrentDirectory(new java.io.File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter(("*.image"), "jpg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION)
        {
            
            try {
                java.io.File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                // path ss=new Path(""+selectedFile.getAbsoluteFile());
                //Path sss=ne(""+selectedFile.getAbsoluteFile());
                 s=path;
                String ss= selectedFile.getAbsolutePath();
                
//copy source to target using Files Class
                
                lbl_pic.setIcon(ResizeImage(path,null));
            } catch (Exception ex) {
                //Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            System.out.println("no file selected");
        }

    }//GEN-LAST:event_btn_uploadActionPerformed

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
        //String s = dateChooserCombo1.getText();

        dob.setText(dateChooserCombo1.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Connection con = null;
PreparedStatement pst = null;
PreparedStatement pst1 = null;
 ResultSet rs =null;
 try {
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        con=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dell\\Documents\\NetBeansProjects\\JavaApplication1\\Studentaddmi.accdb");
        if (jComboBox1.getSelectedItem().toString().equals("5th")) {
        String sql ="Update  fifth set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
        if (jComboBox1.getSelectedItem().toString().equals("6th")) {
        String sql ="Update  sixth set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
        if (jComboBox1.getSelectedItem().toString().equals("7th")) {
        String sql ="Update  seventh set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
        if (jComboBox1.getSelectedItem().toString().equals("8th")) {
        String sql ="Update  eigth set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
        if (jComboBox1.getSelectedItem().toString().equals("9th")) {
        String sql ="Update  ninth set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
        if (jComboBox1.getSelectedItem().toString().equals("10th")) {
        String sql ="Update  tenth set pic=? where  stud_ID = '"+txtsearch.getText()+"' ";  
        pst=con.prepareCall(sql);
   //rs=pst1.executeQuery();
    InputStream is = new FileInputStream(new File (s));
        
     pst.setString(1,s  );
    //  pst.setString(2,surname.getText());
       
           pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null,"Update Sussesfuly");
        }
 }catch(Exception e){ JOptionPane.showMessageDialog(null, e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);      
new MainMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void teleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add2;
    private javax.swing.JTextField address;
    private javax.swing.JTextField apt;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btn_upload;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lbl_pic;
    private javax.swing.JComboBox medi;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tele;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
